// Centralized help text registry per-locale. Extend as needed.
export const helpTexts = {
  en: {
    // Common
    generic_required: 'This field is required.',
    search_global: 'Search any page by name and jump quickly.',
    language_switcher: 'Switch application language between English and Urdu.',
    // Sales
    sales_pos: 'Open the Point of Sale screen to create new sales.',
    sales_customers: 'Manage customers and their profiles.',
    sales_history: 'View a customer\'s historical purchases.',
    pricing_rules: 'Define discounts and price adjustments.',
    // Purchases
    vendors: 'Manage suppliers used for purchases.',
    purchases: 'Record purchases from vendors and update inventory.',
    expenses: 'Track operating expenses and payments.',
    // Inventory
    products: 'Create and manage products and SKUs.',
    categories: 'Organize products into categories.',
    adjustments: 'Adjust stock levels due to loss, damage or corrections.',
    inventory_loans: 'Track inventory items loaned out and returns.',
    inventory_report: 'Inventory quantities and valuation.',
    inventory_average: 'Average cost calculation details.',
    // Accounting
    ledger: 'View ledger accounts and balances.',
    journals: 'List of journal entries posted to the ledger.',
    trial_balance: 'Trial balance report for all accounts.',
    profit_loss: 'Income statement for a selected period.',
    // Finance
    finance_summary: 'Overview of financial KPIs and summaries.',
    // Admin
    shops: 'Manage shops/branches and settings.',
    // Product form
    product_name: 'Enter the product display name customers will see.',
    product_sku: 'Unique stock keeping unit to identify the product.',
    product_description: 'Optional description to help staff/customers.',
    product_price: 'Selling price per unit. Taxes may apply separately.',
    product_stock: 'Initial on-hand quantity being recorded.',
    product_tax_rate: 'Percentage tax to apply (e.g., 17 for 17%).',
    product_category: 'Optional category for organizing products.',
    product_is_active: 'Inactive products are hidden from POS and listings.',
    // Reports: Sales
    sales_report_title: 'Sales within the selected date range, including walk-in and regular customers.',
    sales_filter_from: 'Start date for the report window.',
    sales_filter_to: 'End date for the report window.',
    sales_avg_sold_price: 'Weighted average of unit selling prices (by quantity) over the period.',
    sales_units_original: 'Units sold without line-level discount.',
    sales_units_discounted: 'Units sold with a discounted unit price.',
    sales_th_id: 'Internal sale ID.',
    sales_th_date: 'Sale creation date and time.',
    sales_th_customer: 'Customer name, or Walk-in if not specified.',
    sales_th_type: 'Walk-in vs Regular (has a customer record).',
    sales_th_items: 'Number of distinct items on the sale.',
    sales_th_units: 'Total units sold across all items.',
    sales_th_paid: 'Amount received for this sale.',
    sales_th_payment: 'Payment status (paid/partial/unpaid).',
    sales_th_total: 'Gross total including tax.',
    sales_dc_customer: 'Customer receiving the discount.',
    sales_dc_line_discount: 'Sum of line-level discounts.',
    sales_dc_header_discount: 'Sum of header-level discounts.',
    sales_dc_total_discount: 'Total discount by customer.',
    sales_dp_product: 'Product receiving the discount.',
    sales_dp_line_discount: 'Total line-level discount by product.',
    // Reports: Purchases
    purchases_total_spend: 'Total amount spent on purchases in the period.',
    purchases_total_qty: 'Total units purchased in the period.',
    purchases_avg_unit_cost: 'Average purchase unit cost.',
    purchases_outstanding: 'Outstanding payables for purchases.',
    purchases_avg_daily_spend: 'Average daily spend on purchases.',
    purchases_avg_daily_qty: 'Average daily quantity purchased.',
    purchases_weekly_avg_spend: 'Average weekly spend on purchases.',
    purchases_monthly_avg_spend: 'Average monthly spend on purchases.',
    purchases_over_time: 'Spend (line) and Quantity (bars) over time.',
    purchases_top_vendors: 'Vendors with the highest spend.',
    purchases_top_products: 'Products most purchased by units and spend.',
    purchases_th_vendor: 'Vendor name.',
    purchases_th_purchases: 'Number of purchase orders.',
    purchases_th_units: 'Total purchased units.',
    purchases_th_avg_unit: 'Average unit cost.',
    purchases_th_spend: 'Total spend with vendor.',
    purchases_th_product: 'Product name.',
    purchases_th_total_cost: 'Total cost for product purchases.',
    purchases_th_datetime: 'Purchase date and time.',
    purchases_th_items: 'Number of distinct items in the purchase.',
    purchases_th_subtotal: 'Subtotal before tax and other charges.',
    purchases_th_tax: 'Total tax on purchase.',
    purchases_th_other: 'Other charges applied.',
    purchases_th_total: 'Grand total including all charges.',
    purchases_th_paid: 'Amount paid towards the purchase.',
    purchases_th_status: 'Payment status of the purchase.',
  },
  ur: {
    // Common
    generic_required: 'یہ فیلڈ لازمی ہے۔',
    search_global: 'کسی بھی صفحہ کا نام تلاش کریں اور فوراً جائیں۔',
    language_switcher: 'ایپ کی زبان انگریزی اور اردو کے درمیان تبدیل کریں۔',
    // Sales
    sales_pos: 'نئی سیلز بنانے کے لیے پی او ایس اسکرین کھولیں۔',
    sales_customers: 'کسٹمرز اور ان کی پروفائلز منظم کریں۔',
    sales_history: 'کسٹمر کی سابقہ خریداری دیکھیں۔',
    pricing_rules: 'ڈسکاؤنٹس اور قیمت میں تبدیلیاں سیٹ کریں۔',
    // Purchases
    vendors: 'سپلائرز کو منظم کریں جو خریداری کے لیے استعمال ہوتے ہیں۔',
    purchases: 'ویینڈرز سے خریداری ریکارڈ کریں اور انوینٹری اپڈیٹ کریں۔',
    expenses: 'آپریٹنگ اخراجات اور ادائیگیاں ٹریک کریں۔',
    // Inventory
    products: 'مصنوعات اور ایس کے یوز بنائیں اور منظم کریں۔',
    categories: 'مصنوعات کو کیٹیگریز میں منظم کریں۔',
    adjustments: 'نقصان، خرابی یا تصحیح کی وجہ سے اسٹاک کی سطح ایڈجسٹ کریں۔',
    inventory_loans: 'ادھار دی گئی انوینٹری اور واپسی کو ٹریک کریں۔',
    inventory_report: 'انوینٹری مقدار اور ویلیوایشن۔',
    inventory_average: 'اوسط لاگت کے حساب کی تفصیلات۔',
    // Accounting
    ledger: 'لیجر اکاؤنٹس اور بیلنس دیکھیں۔',
    journals: 'لیجر میں پوسٹ کردہ جرنل اندراجات کی فہرست۔',
    trial_balance: 'تمام اکاؤنٹس کے لیے ٹرائل بیلنس رپورٹ۔',
    profit_loss: 'منتخب مدت کے لیے منافع و نقصان کا بیان۔',
    // Finance
    finance_summary: 'مالیاتی کے پی آئیز اور خلاصوں کا جائزہ۔',
    // Admin
    shops: 'شاپس/برانچز اور سیٹنگز منظم کریں۔',
    // Product form
    product_name: 'وہ نام درج کریں جو کسٹمرز دیکھیں گے۔',
    product_sku: 'مصنوعات کی منفرد شناخت کے لیے ایس کے یو۔',
    product_description: 'اختیاری تفصیل جو عملہ/کسٹمرز کی مدد کرے۔',
    product_price: 'فی یونٹ سیلنگ قیمت۔ ٹیکس الگ سے لاگو ہو سکتا ہے۔',
    product_stock: 'موجودہ اسٹاک کی ابتدائی مقدار۔',
    product_tax_rate: 'لاگو ٹیکس فیصد (مثلاً 17 کا مطلب 17%).',
    product_category: 'مصنوعات کو منظم کرنے کے لیے اختیاری کیٹیگری۔',
    product_is_active: 'غیر فعال مصنوعات پی او ایس اور فہرستوں میں نظر نہیں آئیں گی۔',
    // Reports: Sales
    sales_report_title: 'منتخب مدت میں سیلز، جس میں واک اِن اور ریگولر کسٹمرز شامل ہیں۔',
    sales_filter_from: 'رپورٹ کی مدت کی ابتداء کی تاریخ۔',
    sales_filter_to: 'رپورٹ کی مدت کی اختتامی تاریخ۔',
    sales_avg_sold_price: 'مدت کے دوران یونٹ فروخت قیمتوں کا وزن شدہ اوسط (مقدار کے لحاظ سے)۔',
    sales_units_original: 'وہ یونٹس جن پر لائن لیول ڈسکاؤنٹ نہیں تھا۔',
    sales_units_discounted: 'وہ یونٹس جن پر کم کی گئی یونٹ قیمت تھی۔',
    sales_th_id: 'اندرونی سیل آئی ڈی۔',
    sales_th_date: 'سیل کی تاریخ اور وقت۔',
    sales_th_customer: 'کسٹمر کا نام، یا واک اِن اگر مخصوص نہ ہو۔',
    sales_th_type: 'واک اِن بمقابلہ ریگولر (کسٹمر ریکارڈ کے ساتھ)۔',
    sales_th_items: 'سیل پر مختلف آئٹمز کی تعداد۔',
    sales_th_units: 'تمام آئٹمز میں بیچی گئی کل یونٹس۔',
    sales_th_paid: 'اس سیل کے لیے وصول شدہ رقم۔',
    sales_th_payment: 'ادائیگی کی حیثیت (ادا شدہ/جزوی/غیر ادا شدہ)۔',
    sales_th_total: 'ٹیکس سمیت مجموعی رقم۔',
    sales_dc_customer: 'ڈسکاؤنٹ لینے والا کسٹمر۔',
    sales_dc_line_discount: 'لائن لیول ڈسکاؤنٹس کا مجموعہ۔',
    sales_dc_header_discount: 'ہیڈر لیول ڈسکاؤنٹس کا مجموعہ۔',
    sales_dc_total_discount: 'کسٹمر کے لحاظ سے کل ڈسکاؤنٹ۔',
    sales_dp_product: 'ڈسکاؤنٹ لینے والی پروڈکٹ۔',
    sales_dp_line_discount: 'پروڈکٹ کے لحاظ سے لائن لیول ڈسکاؤنٹ۔',
    // Reports: Purchases
    purchases_total_spend: 'مدت میں خریداری پر خرچ کی گئی کل رقم۔',
    purchases_total_qty: 'مدت میں خریدی گئی کل یونٹس۔',
    purchases_avg_unit_cost: 'اوسط خریداری یونٹ لاگت۔',
    purchases_outstanding: 'خریداری کی واجب الادا رقم۔',
    purchases_avg_daily_spend: 'روزانہ کی اوسط خریداری خرچ۔',
    purchases_avg_daily_qty: 'روزانہ کی اوسط خریدی گئی مقدار۔',
    purchases_weekly_avg_spend: 'ہفتہ وار اوسط خریداری خرچ۔',
    purchases_monthly_avg_spend: 'ماہانہ اوسط خریداری خرچ۔',
    purchases_over_time: 'وقت کے ساتھ خرچ (لائن) اور مقدار (بارز)۔',
    purchases_top_vendors: 'زیادہ خرچ والے ویینڈرز۔',
    purchases_top_products: 'سب سے زیادہ خریدی جانے والی مصنوعات۔',
    purchases_th_vendor: 'ویینڈر کا نام۔',
    purchases_th_purchases: 'خریداری آرڈرز کی تعداد۔',
    purchases_th_units: 'کل خریدی گئی یونٹس۔',
    purchases_th_avg_unit: 'اوسط یونٹ لاگت۔',
    purchases_th_spend: 'ویینڈر کے ساتھ کل خرچ۔',
    purchases_th_product: 'پروڈکٹ کا نام۔',
    purchases_th_total_cost: 'پروڈکٹ خریداری کی کل لاگت۔',
    purchases_th_datetime: 'خریداری کی تاریخ اور وقت۔',
    purchases_th_items: 'خریداری میں مختلف آئٹمز کی تعداد۔',
    purchases_th_subtotal: 'ٹیکس اور دیگر چارجز سے پہلے سب ٹوٹل۔',
    purchases_th_tax: 'خریداری پر کل ٹیکس۔',
    purchases_th_other: 'لاگو دیگر چارجز۔',
    purchases_th_total: 'تمام چارجز سمیت مجموعی رقم۔',
    purchases_th_paid: 'خریداری کی ادائیگی کی گئی رقم۔',
    purchases_th_status: 'خریداری کی ادائیگی کی حیثیت۔',
  }
};

export function getHelpText(locale, key) {
  return (helpTexts[locale] && helpTexts[locale][key]) || (helpTexts.en && helpTexts.en[key]) || '';
}
